/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as settingsLogsRouteImport } from './routes/(settings)/logs'
import { Route as settingsDebugRouteImport } from './routes/(settings)/debug'
import { Route as settingsConfigRouteImport } from './routes/(settings)/config'
import { Route as proxySkillsRouteImport } from './routes/(proxy)/skills'
import { Route as proxyProxyRouteImport } from './routes/(proxy)/proxy'
import { Route as proxyNodesRouteImport } from './routes/(proxy)/nodes'
import { Route as controlUsageRouteImport } from './routes/(control)/usage'
import { Route as controlSessionsRouteImport } from './routes/(control)/sessions'
import { Route as controlOverviewRouteImport } from './routes/(control)/overview'
import { Route as controlInstancesRouteImport } from './routes/(control)/instances'
import { Route as controlCronRouteImport } from './routes/(control)/cron'
import { Route as controlChannelsRouteImport } from './routes/(control)/channels'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsLogsRoute = settingsLogsRouteImport.update({
  id: '/(settings)/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsDebugRoute = settingsDebugRouteImport.update({
  id: '/(settings)/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const settingsConfigRoute = settingsConfigRouteImport.update({
  id: '/(settings)/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const proxySkillsRoute = proxySkillsRouteImport.update({
  id: '/(proxy)/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const proxyProxyRoute = proxyProxyRouteImport.update({
  id: '/(proxy)/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const proxyNodesRoute = proxyNodesRouteImport.update({
  id: '/(proxy)/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const controlUsageRoute = controlUsageRouteImport.update({
  id: '/(control)/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const controlSessionsRoute = controlSessionsRouteImport.update({
  id: '/(control)/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const controlOverviewRoute = controlOverviewRouteImport.update({
  id: '/(control)/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const controlInstancesRoute = controlInstancesRouteImport.update({
  id: '/(control)/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const controlCronRoute = controlCronRouteImport.update({
  id: '/(control)/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const controlChannelsRoute = controlChannelsRouteImport.update({
  id: '/(control)/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/channels': typeof controlChannelsRoute
  '/cron': typeof controlCronRoute
  '/instances': typeof controlInstancesRoute
  '/overview': typeof controlOverviewRoute
  '/sessions': typeof controlSessionsRoute
  '/usage': typeof controlUsageRoute
  '/nodes': typeof proxyNodesRoute
  '/proxy': typeof proxyProxyRoute
  '/skills': typeof proxySkillsRoute
  '/config': typeof settingsConfigRoute
  '/debug': typeof settingsDebugRoute
  '/logs': typeof settingsLogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/channels': typeof controlChannelsRoute
  '/cron': typeof controlCronRoute
  '/instances': typeof controlInstancesRoute
  '/overview': typeof controlOverviewRoute
  '/sessions': typeof controlSessionsRoute
  '/usage': typeof controlUsageRoute
  '/nodes': typeof proxyNodesRoute
  '/proxy': typeof proxyProxyRoute
  '/skills': typeof proxySkillsRoute
  '/config': typeof settingsConfigRoute
  '/debug': typeof settingsDebugRoute
  '/logs': typeof settingsLogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chat': typeof ChatRoute
  '/(control)/channels': typeof controlChannelsRoute
  '/(control)/cron': typeof controlCronRoute
  '/(control)/instances': typeof controlInstancesRoute
  '/(control)/overview': typeof controlOverviewRoute
  '/(control)/sessions': typeof controlSessionsRoute
  '/(control)/usage': typeof controlUsageRoute
  '/(proxy)/nodes': typeof proxyNodesRoute
  '/(proxy)/proxy': typeof proxyProxyRoute
  '/(proxy)/skills': typeof proxySkillsRoute
  '/(settings)/config': typeof settingsConfigRoute
  '/(settings)/debug': typeof settingsDebugRoute
  '/(settings)/logs': typeof settingsLogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chat'
    | '/channels'
    | '/cron'
    | '/instances'
    | '/overview'
    | '/sessions'
    | '/usage'
    | '/nodes'
    | '/proxy'
    | '/skills'
    | '/config'
    | '/debug'
    | '/logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chat'
    | '/channels'
    | '/cron'
    | '/instances'
    | '/overview'
    | '/sessions'
    | '/usage'
    | '/nodes'
    | '/proxy'
    | '/skills'
    | '/config'
    | '/debug'
    | '/logs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chat'
    | '/(control)/channels'
    | '/(control)/cron'
    | '/(control)/instances'
    | '/(control)/overview'
    | '/(control)/sessions'
    | '/(control)/usage'
    | '/(proxy)/nodes'
    | '/(proxy)/proxy'
    | '/(proxy)/skills'
    | '/(settings)/config'
    | '/(settings)/debug'
    | '/(settings)/logs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChatRoute: typeof ChatRoute
  controlChannelsRoute: typeof controlChannelsRoute
  controlCronRoute: typeof controlCronRoute
  controlInstancesRoute: typeof controlInstancesRoute
  controlOverviewRoute: typeof controlOverviewRoute
  controlSessionsRoute: typeof controlSessionsRoute
  controlUsageRoute: typeof controlUsageRoute
  proxyNodesRoute: typeof proxyNodesRoute
  proxyProxyRoute: typeof proxyProxyRoute
  proxySkillsRoute: typeof proxySkillsRoute
  settingsConfigRoute: typeof settingsConfigRoute
  settingsDebugRoute: typeof settingsDebugRoute
  settingsLogsRoute: typeof settingsLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(settings)/logs': {
      id: '/(settings)/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof settingsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(settings)/debug': {
      id: '/(settings)/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof settingsDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(settings)/config': {
      id: '/(settings)/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof settingsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proxy)/skills': {
      id: '/(proxy)/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof proxySkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proxy)/proxy': {
      id: '/(proxy)/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof proxyProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(proxy)/nodes': {
      id: '/(proxy)/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof proxyNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/usage': {
      id: '/(control)/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof controlUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/sessions': {
      id: '/(control)/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof controlSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/overview': {
      id: '/(control)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof controlOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/instances': {
      id: '/(control)/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof controlInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/cron': {
      id: '/(control)/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof controlCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(control)/channels': {
      id: '/(control)/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof controlChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  controlChannelsRoute: controlChannelsRoute,
  controlCronRoute: controlCronRoute,
  controlInstancesRoute: controlInstancesRoute,
  controlOverviewRoute: controlOverviewRoute,
  controlSessionsRoute: controlSessionsRoute,
  controlUsageRoute: controlUsageRoute,
  proxyNodesRoute: proxyNodesRoute,
  proxyProxyRoute: proxyProxyRoute,
  proxySkillsRoute: proxySkillsRoute,
  settingsConfigRoute: settingsConfigRoute,
  settingsDebugRoute: settingsDebugRoute,
  settingsLogsRoute: settingsLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
